trigger:
- master

jobs:
  - job: testrunnerToolkit
    variables:
      SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
      SAUCE_USERNAME: $(SAUCE_USERNAME)
      CI: true
    pool:
      vmImage: 'ubuntu-latest'
    container: saucelabs/stt-puppeteer-jest-node:latest
    
    steps:
    - checkout: self
      displayName: 'Checkout Code'
    - task: NodeTool@0
      inputs:
        versionSpec: 12.x
    - script: npm install
      displayName: 'Install node dependencies'
    - script: saucectl run -c ./.sauce/puppeteer.yml
      displayName: 'Run Testrunner Toolkit'
