version: 2.1
jobs:
  test-cypress:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/repo
    environment:
      SAUCECTL_VERSION: 0.19.0
      SAUCECTL_BINARY: saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - v1-npm-deps-{{ checksum "package.json" }}
#            - v1-npm-deps-
#      - run:
#          name: Install Dependencies
#          command: npm install
#      - run:
#          name: Build Project
#          command: |
#            npm run build
#      - save_cache:
#          paths:
#            - ./node_modules
#          key: v1-npm-deps-{{ checksum "package.json" }}
      - run:
          name: Download Saucectl
          command: |
            curl -L -o $SAUCECTL_BINARY \
            -H "Accept: application/octet-stream" \
            "https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/${SAUCECTL_BINARY}" \
            && tar -xvzf $SAUCECTL_BINARY
      - run:
          name: Cypress Tests
          command: |
            saucectl run -c ./.sauce/cypress.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI
workflows:
  version: 2
  default_workflow:
    jobs:
      - test-cypress