# runs parallel cypress tests with Testrunner Toolkit
name: STT Cypress Parallel

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  cypress-parallel-1:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-cypress-mocha-node
      options: --user 1001

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/cypress_parallel.yml --verbose
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: Github Actions

  cypress-parallel-2:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-cypress-mocha-node
      options: --user 1001

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/cypress_parallel.yml --verbose
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: Github Actions