# runs parallel cypress tests with Testrunner Toolkit
name: Sauce Pipeline Browser Tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  basic:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine

    steps:
      - name: Install Dependencies
        run: apk add --no-cache git gcc g++ curl

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          go install ./...
          go get -u github.com/mcubik/goverreport
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
          CGO_ENABLED=0 go build cmd/saucectl/saucectl.go
      - name: Lint project
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...
      - name: Run tests
        run: |
          go test -coverprofile=coverage.out ./...
          goverreport -sort=block -order=desc -threshold=45
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: saucectlbin
          path: saucectl

  cypress-parallel-1:
    needs: basic
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-cypress-mocha-node
      options: --user 1001

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Download saucectl binary
        uses: actions/download-artifact@v2
        with:
          name: saucectlbin

      - name: Run Sauce Pipeline Test
        run: |
          chmod +x ./saucectl
          ./saucectl run -c ./.sauce/cypress_parallel.yml --verbose
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: Github Actions
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  cypress-parallel-2:
    needs: basic
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-cypress-mocha-node
      options: --user 1001

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Download saucectl binary
        uses: actions/download-artifact@v2
        with:
          name: saucectlbin

      - name: Run Sauce Pipeline Test
        run: |
          chmod +x ./saucectl
          ./saucectl run -c ./.sauce/cypress_parallel.yml --verbose
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: Github Actions
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
